# ##################### #
# # MPT Configuration # #
# ##################### #

# If true, detailed but potentially unneeded logging information will be printed to the console.
verbose: false

# If true, package archives will be kept in the plugin cache after installing.
keep-archives: false

# When true, the plugin will automatically keep itself up-to-date.
auto-update: true

# When true, the plugin will submit anonymous statistics to mcstats.org
metrics: true

########################################################################
# Options below this marker are there for your protection.             #
# Please know that by changing them you are doing so at your own risk. #
########################################################################

# If true, package checksums will be compared against the downloaded content, and installation of packages without
# an expected checksum will be prevented.
# It is HIGHLY recommended that you leave this true unless you understand the implications and know that you do so at
# your own risk.
enforce-checksum: true

# While true, files in the root of downloaded archives will not be extracted if they already exist in the server root.
# It is HIGHLY recommended you leave this true to protect against potential exploits of the content-delivery system.
# Note: this does not apply to directories.
disallow-overwrite: true

# While true, directories will not be merged if they already exist.
disallow-merge: false

# Files with extensions present on this list will not be extracted no matter what. It is HIGHLY recommended that you
# not remove any present by default.
disallowed-extensions:
  - jar
  - class
  - java
  - exe
  - msi
  - application
  - deb
  - rpm

# Files within directories contained by the following list will not be extracted no matter what.
disallowed-directories:
  - plugins
  - world
  - world_nether
  - world_the_end
