name: MPT
version: 0.1.0-SNAPSHOT%VERSION%
main: net.amigocraft.mpt.Main
description: A Bukkit plugin similar to Debian's apt-get package, but with Minecraft maps instead of packages.
author: Maxim Roncacé

commands:
  mpt:
    description: The primary plugin command.
    usage: /mpt [subcommand]

permissions:
  mpt.*:
    description: Grants full access to the plugin's features.
    default: op
    children:
      mpt.addrepo: true
      mpt.remoterepo: true
      mpt.update: true
      mpt.upgrade: true
      mpt.install: true
      mpt.remove: true
      mpt.help: true

  mpt.repos:
    description: Allows the player to add, remove, and update from repositories.
    default: op

  mpt.install:
    description: Allows the player to install, upgrade, and remove packages (maps).
    default: op

  mpt.help:
    description: Allows access to the help window.
    default: op
