name: MPT
version: 1.2.1-SNAPSHOT
main: net.caseif.mpt.Main
description: A Bukkit plugin similar to Debian's apt-get package, but with Minecraft resources instead of packages.
author: Max Roncacé

commands:
  mpt:
    description: The primary plugin command.
    usage: /mpt [subcommand]

permissions:
  mpt.*:
    description: Grants full access to the plugin's features.
    default: op
    children:
      mpt.use: true
      mpt.abort: true
      mpt.help: true

  mpt.use:
    description: Allows the player to view, add, modify, and remove packages and repositories, and to reload the plugin.
    default: op

  mpt.abort:
    description: Allows the player to abort currently running MPT tasks.
    default: op

  mpt.help:
    description: Allows access to the help window.
    default: op
